title: generic-python-turtle-new
hero_image: images/banner.png
description: generic-python-turtle-new description
original_url: 
theme: cc-prototype
duration: 1 # 1, 2 or 3
listed: false
ingredient: true
copyedit: false
interests: "graphics"
technologies: "python, turtle"
steps:
  - title: New turtle
