title: Create a new turtle in Python
hero_image: images/banner.png
description: How to add new turtles on the screen
original_url: 
theme: cc-prototype
duration: 1 # 1, 2 or 3
listed: false
ingredient: true
copyedit: false
interests: "graphics"
technologies: "python, turtle"
steps:
  - title: New turtle
